const express = require('express')
const app = express()
app.use(express.json())
const bookController = require('../controllers/book.controller')
const {midOne} = require('../middlewares/simple-middleware')
app.get("/",[midOne],bookController.getAllBook)
app.post("/find",bookController.findBook)
app.post("/",bookController.addBook)
app.put("/:id",bookController.updateBook)
app.delete("/:id",bookController.deleteBook)
module.exports=app